### ISSUE TITLE
ds18x20 configuration

### ISSUE THREAD

**Issue by DanielDecker** [rkoshak/sensorReporter#106]
I opened this issue because there seems to be a bug with the `ds18x20` sensor and I think its better to discuss it here rather than in a merged PR #105  

>The original/old configuration did not work due to the MQTT Homie changes, so if both should, we need to fix this.

_Originally posted by @florian-h05 in https://github.com/rkoshak/sensorReporter/pull/105#discussion_r1225866668_

I wrote:
>I deliberately designed the Homie support that way, that the config for a sensor with single output doesn't need to specify the channel. So sensorReporter will assume that the given StateDest is reverencing the only available channel.
So, in my opinion, both configurations (with and without channel) are correct in this case.

To clarify, this is nothing Homie specific, I was wrong in the comment above. The sensor channel structure it related to the yaml configuration and the way it is read.
After reviewing the code again, I must also state, that there is no auto selection for sensors with single output. There are single output sensors that don't require the channel to be defined and I took this for auto selection.

Actually it depends on the sensor implementation if a channel must be specified or not. taken from exec_sensor:
```python
self._send(self.results, self.comm)
```
In the example above are only two arguments specified, the third argument which defines the trigger (channel) is omitted so there is no need to define a channel in the config.
In the ds18x20 sensor this looks as following
```python
OUT_TEMP = "Temperature"
self._send(to_send, self.comm, OUT_TEMP)
```
Since the "trigger argument" is set to "Temperature" the configuration must specify this channel.

So there are two approaches:
1. change the ds18x20 code and documentation, so that no extra channel is needed in the configuration. This would be consistent with the other sensors
2. leave the ds18x20 code and documentation unchanged

For the sake of completeness:
If the sensor implementation uses the trigger argument in the `send` command `configure_device_channel` must also specify the channel via `output_name`:
```python
configure_device_channel(self.comm, is_output=True, output_name=OUT_TEMP,
                                 datatype=ChanType.FLOAT, name="temperatur reading",
                                 unit="°" + self.temp_unit)
```

**Comment by florian-h05** [comment]
I would vote for option 1:

> change the ds18x20 code and documentation, so that no extra channel is needed in the configuration. This would be consistent with the other sensors.

> If the sensor implementation uses the trigger argument in the send command configure_device_channel must also specify the channel via output_name:

... and in the YAML config. The method docs for send and configure_device_channel should be updated to mention this.

**Comment by DanielDecker** [comment]
OK, I'll prepare a PR to make this sensor consistent and update the docs for `send` and `configure_device_channel`
