### ISSUE TITLE
install script - raspi-config integration

### ISSUE THREAD

**Issue by DanielDecker** [rkoshak/sensorReporter#122]
Not a request, just a question. Could this be implemented as part of the install scripts? Obviously calling raspi-config isn't going to work but I think all that does is set a flag in a file somewhere.

_Originally posted by @rkoshak in https://github.com/rkoshak/sensorReporter/pull/121#discussion_r1519812974_

Good point, I hadn't thought of that. I actually forgot to enable I2C several times when testing the install script.
The raspi-config actually has a [non interactive mode](https://www.raspberrypi.com/documentation/computers/configuration.html#interfacing-options-nonint) (nonint), so the i2c or 1-wire interface (Ds18x20Sensor) can be enabled or disabled with a single command.
E.g. enable i2c
`sudo raspi-config nonint do_i2c 0`

Yes it can be integrated in the install script.
Should I prepare a PR?

**Comment by rkoshak** [comment]
That would be great! If you forgot I'm certain others would too. We do so much for them in the install script, it seems off to not do this if it's feasible.

**Comment by DanielDecker** [comment]
> If you forgot I'm certain others would too.

So true!
I'll prepare a PR.

**Comment by DanielDecker** [comment]
PR was merged, so this issue is solved!
