### ISSUE TITLE
GPIO4 blocked unintentionally

### ISSUE THREAD

**Issue by DanielDecker** [rkoshak/sensorReporter#131]
Running `sudo ./install_dependencies.sh gpio` to install any of the dependencies in the GPIO folder will setup the 1-Wire interface for the Ds18x20Sensor as intended. The 1-Wire driver uses GPIO4 ([default setting](https://pinout.xyz/pinout/1_wire)), which will then no longer be available for any other GPIO device.

This is currently not documented in the readme and can lead to confusion if the Ds18x20Sensor isn't used at all.
I think the cleanest solution would be to move the Ds18x20Sensor into its own folder (e.g. `1-wire`) with its own dependencies.txt, but this would introduce a breaking change.
What do you think?

**Comment by rkoshak** [comment]
That makes sense. Blocking GPIO4 is already a breaking change so fixing that with a breaking change feels like an even trade.
