### ISSUE TITLE
More about TLS

### ISSUE THREAD

**Issue by ghost** [rkoshak/sensorReporter#27]
Hi Richard,

I use you project to detect by bluetooth who is present in my house or elsewhere. Thank you for that it's working as I would with my rpi 3.

As usually, I try to secure my installation. 

It seems the TLS part is incomplete in your project if I understand well. 

May I suggest you to add some more options in your config file ?

For example about TLS:

TLS = YES # YES or NO as before
TLS Protocol version = 1.2 # here you can allow 1.0 (the default in paho mqtt) or 1.1 or 1.2 
TLS certs directory = /opt/sensorReporter # no comment
Check TLS subject name = False

For this new option you will need:

`self.client.tls_set("/opt/sensorReporter/certs/ca.crt","/opt/sensorReporter/certs/OH_secu.crt","/opt/sensorReporter/certs/OH_secu.key",tls_version=ssl.PROTOCOL_TLSv1_1)`

Have to adapt the path to certs directory and change for tls version the last number. Beware if tls_version is not present it's TLS version 1 which is used by default.

As usually for a tls connection, you need the certificate authority, and client certificate (key and crt)

`self.client.tls_insecure_set(True)`
Is used to check if subject name in certificate match. If used with false this is ignored.

Add in mqttConn.py: `import ssl`

What do you think about that ? I'm using it and it's functional. It's better too have a secure connection, no ?

Gilles.

**Comment by rkoshak** [comment]
I will look into this. If you are willing to submit a PR I will accept it. I'm currently running my Broker in a Docker container and my SSL certs change every time I reboot and until I fix that I won't be able to test and/or complete the SSL implementation.
