### ISSUE TITLE
Support BLE

### ISSUE THREAD

**Issue by tigre-bleu** [rkoshak/sensorReporter#40]
As far as I understand, sensorReporter can scan for legacy bluetooth devices. It would be nice to also include BLE in order to support low energy BLE tags.

I own a few attached to keys or objetcs and I use them for presence detection.

**Comment by rkoshak** [comment]
I recommend using reelyActive to scan for and report on BTLE devices. That system will always be far more capable and far more complete than anything I could hope to do in sensorReporter.  If you are coming from OH, or use MQTT, search the openHAB forum for "reelyActive revisited" for how to set it up to report presence via MQTT.
