### ISSUE TITLE
 [rpiGPIOActuator.py] ON and OFF msg commands do not work

### ISSUE THREAD

**Issue by bgilmer77** [rkoshak/sensorReporter#55]
Sending any message to the topic for the actuator causes a toggle if toggle is set to true.  Setting toggle to false and then sending either NO or YES to the MQTT topic causes a message such as, `2018-03-23 15:00:50,987 ERROR - Bad input <paho.mqtt.client.MQTTMessage object at 0xb66014b0>
`
Problem appears to be that the IF statements such as:
`if msg == "ON"`

never match.

**Comment by bgilmer77** [comment]
Additional information - the variable `msg` contains values such as the following:

`<paho.mqtt.client.MQTTMessage object at 0xb659f4b0>`


I think it is supposed to contain the actual message such to the topic, such as `ON`.

**Comment by rkoshak** [comment]
This should be fixed now. Please test it too and tell me whether it works or not. Thanks.

**Comment by bgilmer77** [comment]
Thanks Rich!!  I have a pretty hectic travel schedule coming up, but when I get a chance to check this out I will report back.  I really appreciate your working on this. Would have fixed it myself but did not know about the '.payload'.

**Comment by rkoshak** [comment]
I'm going to close this issue. If it is still a problem please reopen.
