### ISSUE TITLE
Heartbeat.py does not send frequent messages

### ISSUE THREAD

**Issue by dersch81** [rkoshak/sensorReporter#65]
Hi, by using /device/getUpdate i get messages back of /status/heartbeat and /status/hearbeatstr (there is a typo) but normally i should get it every hr (3600000ms) but it does not work. I always need to ask.

**Comment by rkoshak** [comment]
Can you provide more information. What communicator are you using? What is the .ini config of the heartbat plugin?

**Comment by dersch81** [comment]
i'm using mosquitto 

the .ini config of the heartbeat is

`[Sensor2]
Class = heartbeat.heartbeat
Type = Heartbeat
Connection = MQTT
Poll = 3600000
; The number of milliseconds sensorReporter has been online is published to this destination
Num-Dest = klopi/heartbeat
Str-Dest = klopi/hearbeatstr
`

**Comment by rkoshak** [comment]
I've just done a rewrite of sensor_reporter. I have struggled to figure out why you saw the behavior you saw. Now, more than a year later I realize the problem. The Poll is seconds, not milliseconds. 

I think I've addressed this issue with the new documentation.

**Comment by dersch81** [comment]
OK :) that's funny. Thank you :D

**Comment by rkoshak** [comment]
Closing as solved by #67
