### ISSUE TITLE
Goove Sensor do not work. Logs show that modules are missing

### ISSUE THREAD

**Issue by idrovof** [rkoshak/sensorReporter#73]
**syslog:**
Error creating device Sensor0: Traceback (most recent call last):#012  File "sensor_reporter.py", line 160, in create_device#012    device = getattr(importlib.import_module(module_name), class_name)#012  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module#012    return _bootstrap._gcd_import(name[level:], package, level)#012  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import#012  File "<frozen importlib._bootstrap>", line 983, in _find_and_load#012  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked#012  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed#012  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import#012  File "<frozen importlib._bootstrap>", line 983, in _find_and_load#012  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked#012ModuleNotFoundError: No module named 'govee'

**python3 sensor_reporter.py configuration.ini**
Traceback (most recent call last):
  File "sensor_reporter.py", line 253, in <module>
    main()
  File "sensor_reporter.py", line 244, in main
    poll_mgr = create_poll_manager(config_file)
  File "sensor_reporter.py", line 184, in create_poll_manager
    init_logger(config)
  File "sensor_reporter.py", line 103, in init_logger
    set_log_level(lambda key: config.get("Logging", key), root_logger)
  File "/opt/sensor_reporter/core/utils.py", line 20, in set_log_level
    level = params("Level")
  File "sensor_reporter.py", line 103, in <lambda>
    set_log_level(lambda key: config.get("Logging", key), root_logger)
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Logging'

**Comment by rkoshak** [comment]
The stacktrace you are showing here shows that you've not defined a Logging section. The Logging section in the .ini file is not optional.

Did you install bleson?

Show your .ini config.
