### ISSUE TITLE
Log level set on class level [bug?]

### ISSUE THREAD

**Issue by DanielDecker** [rkoshak/sensorReporter#90]
I came across that setting the `level` in the config e.g. for a connection will be applied to all connections.
Example config:
```
[Logging]
Syslog = YES
Level = INFO

[Connection1]
Class = openhab_rest.rest_conn.OpenhabREST
Name = openHAB
URL = http://localhost:8080
RefreshItem = Test_Refresh

[Connection2]
Class = openhab_rest.rest_conn.OpenhabREST
Name = openHAB2
URL = http://192.168.1.1:8080
RefreshItem = Test_Refresh
Level = DEBUG
```
In above configuration all connections will be set to log level DEBUG. For sensors and actuators it is the same.
Is this behavior intended?

**Comment by rkoshak** [comment]
You've uncovered an unexpected use case. It never occurred to me that one would want to have more than one connection to openHAB or more than one connection to MQTT at the same time.

It's not all connections, it's all connections of the *same type*.  The logger is "named" based on the class name. So what ever connection is defined last with a Level setting will set the logging level for all connections using the same class (in your case openhab_rest.rest_conn.OpenhabREST). 

That's actually pretty standard logging behavior. In all my years of development I don't think I've ever seen a case where logging has been implemented so each *instance* of a class has it's own logger.

Therefore I'm not in agreement that this is a bug. You've uncovered an unexpected use case but given the amount of effort that will be required to make it work as requested, the rarity of this use case, and that implementing it will result in a non-standard logging behavior I'm going to close this Issue as won't fix.

If you really need this behavior, make a copy of the OpenhabREST class and name it something else and use that copy for Connection2.
