### ISSUE TITLE
debounce possible?

### ISSUE THREAD

**Issue by bks29b** [rkoshak/sensorReporter#98]
Hi. SensorReporter is working fine for me. But I'm missing the debounce feature. Some of my sensors show some bouncing while going from off to on. 

Is it possible to implement this?

Kinds

**Comment by DanielDecker** [comment]
Hi. From your description I assume you're using the RpiGpioSensor. Have you configured it with `EventDetection`? 
If yes try `Poll = 1` instead (remove EventDetection first), this will delay the output for 1s and work as debounce. You can also try a smaller number e. g. 0.5

**Comment by bks29b** [comment]
Ah perfect, missunderstood the poll parameter. I‘ll give it a try. I dont need the Status in realtime, polling will be fine.
